# Generated by Django 3.2.9 on 2022-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_urls_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='shortUrl',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
