# Generated by Django 3.2.16 on 2022-11-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221115_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='title',
        ),
    ]
